In [2]:
import numpy as np

na = np.array([1,2,3,4,5,'d'])

type(na[0])

numpy.str_

In [2]:
v = np.array([1,2,3,4]) # vector 1차원 배열
m = np.array([[1,2],[3,4]])# matrix 2차원
t = np.array([[[1],[2]],[[3],[4]]]) # tensor 3차원
print(v.shape, m.shape, t.shape) # (4,) (2, 2) (2, 2, 1)

(4,) (2, 2) (2, 2, 1)


In [3]:
arr_1d = np.array([1,2,3,4])
arr_1d.shape
arr_1d.ndim

arr_2d = np.array([[1,2], [3,4]], dtype='float')
arr_2d.dtype

dtype('float64')

In [7]:
a=np.array([[1],[2],[3],[4]])
a.shape

(4, 1)

In [8]:
zer = np.zeros(2)
zer2 = np.zeros((3,2))
zer3 = np.zeros((2,3,2))
print(zer)
print('--------------------')
print(zer2)
print('--------------------')
print(zer3)

[0. 0.]
--------------------
[[0. 0.]
 [0. 0.]
 [0. 0.]]
--------------------
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [9]:
arn = np.arange(8)
arn2 = np.arange(2,4) # 시작, 끝
arn3 = np.arange(5,10,2)
print(arn)
print('--------------------')
print(arn2)
print('--------------------')
print(arn3)

[0 1 2 3 4 5 6 7]
--------------------
[2 3]
--------------------
[5 7 9]


In [17]:
np.linspace(1,97,25)

array([ 1.,  5.,  9., 13., 17., 21., 25., 29., 33., 37., 41., 45., 49.,
       53., 57., 61., 65., 69., 73., 77., 81., 85., 89., 93., 97.])

In [18]:
li_1 = [1,2,3]
li_2 = [4,5,6]
li_3 = [7,8,9]
li_0 = [li_1,li_2,li_3]

print(li_0[:1][0])

li = []
for i in range(2):
  li.append(li_0[i][0])

li

[1, 2, 3]


[1, 4]

In [74]:
# 1부터 20까지 숫자를 저장하는 arr
arr = np.arange(1,21)

# 5보다 큰 수만 남도록
arr[arr>5]

# 5보다 크면서 홀수인 수만 남도록
arr[(arr>5) & (arr%2!=0)]

arr.reshape(2,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [103]:
a=np.array([[1,2], [3,4]])
b=np.array([[9,7], [5,3]])
a+b

array([[10,  9],
       [ 8,  7]])

In [152]:

d=np.array(((1,2,3),))
e=np.array(((1,2,3,4),)).reshape(4,1)
print(d, '\n',e)
print(np.ones((4,3)) + d)
print(np.ones((4,3)) + e)

[[1 2 3]] 
 [[1]
 [2]
 [3]
 [4]]
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]
[[2. 2. 2.]
 [3. 3. 3.]
 [4. 4. 4.]
 [5. 5. 5.]]


In [197]:
import numpy as np

arr = np.array([[1,2,3], [2,3,4]])
arr2 = np.array([[1,2,4],[3,2,4]])

np.concatenate((arr, arr2), axis=1)

array([[1, 2, 3, 1, 2, 4],
       [2, 3, 4, 3, 2, 4]])

In [5]:
arr = np.array([9,5,2,3,7,8,9,4]).reshape(2,4)

print(arr)
arr_c = np.sort(arr, axis=0)
arr_r = np.sort(arr, axis=1)

print(arr_c) # [[1 5 2 3], [7 8 9 4]]
print(arr_r) # [[1 2 3 5], [4 7 8 9]]

[[9 5 2 3]
 [7 8 9 4]]
[[7 5 2 3]
 [9 8 9 4]]
[[2 3 5 9]
 [4 7 8 9]]
